-- 코드를 입력하세요

# SELECT A.AUTHOR_ID, A.AUTHOR_NAME, B.CATEGORY, B.PRICE -- SUM(S.SALES) AS 'TOTAL_SALES'
# FROM BOOK B
# JOIN AUTHOR A
# ON B.AUTHOR_ID = A.AUTHOR_ID
# JOIN BOOK_SALES S
# ON  B.BOOK_ID = S.BOOK_ID
# WHERE YEAR(S.SALES_DATE) = '2022' AND MONTH (S.SALES_DATE) = '1'
# GROUP BY B.CATEGORY , A.AUTHOR_ID
# ORDER BY A.AUTHOR_ID, B.CATEGORY DESC;

SELECT DISTINCT A.AUTHOR_ID, A.AUTHOR_NAME, B.CATEGORY, SUM(S.SALES * B.PRICE) OVER(PARTITION BY B.CATEGORY, A.AUTHOR_ID) AS TOTAL_SALES
FROM BOOK B
JOIN AUTHOR A
ON B.AUTHOR_ID = A.AUTHOR_ID
JOIN BOOK_SALES S
ON  B.BOOK_ID = S.BOOK_ID
WHERE YEAR(S.SALES_DATE) = '2022' AND MONTH (S.SALES_DATE) = '1'
ORDER BY A.AUTHOR_ID, B.CATEGORY DESC;