-- 코드를 입력하세요

SELECT P.PRODUCT_CODE, (B.AMOUNT * P.PRICE) AS SALES
FROM PRODUCT P
JOIN (SELECT PRODUCT_ID, SUM(SALES_AMOUNT) AS AMOUNT
FROM OFFLINE_SALE
GROUP BY PRODUCT_ID) B
ON P.PRODUCT_ID = B.PRODUCT_ID
ORDER BY SALES DESC, P.PRODUCT_CODE