-- 코드를 입력하세요
SELECT DISTINCT A.FOOD_TYPE, A.REST_ID, A.REST_NAME, A.FAVORITES 
FROM REST_INFO A
JOIN (SELECT FOOD_TYPE, MAX(FAVORITES) OVER(PARTITION BY FOOD_TYPE) FAVORITES FROM REST_INFO) B
ON A.FAVORITES = B.FAVORITES AND A.FOOD_TYPE = B.FOOD_TYPE
ORDER BY FOOD_TYPE DESC