-- 코드를 작성해주세요
SELECT CONCAT(quarter(DIFFERENTIATION_DATE), 'Q') AS QUARTER, COUNT(*) AS ECOLI_COUNT
FROM ECOLI_DATA
WHERE DIFFERENTIATION_DATE IS NOT NULL
GROUP BY CONCAT(quarter(DIFFERENTIATION_DATE), 'Q')
ORDER BY CONCAT(quarter(DIFFERENTIATION_DATE), 'Q')