-- 코드를 입력하세요
SELECT P.PRODUCT_ID, P.PRODUCT_NAME, P.PRICE * O.AMOUNT TOTAL_SALES FROM FOOD_PRODUCT P 
JOIN (SELECT O.PRODUCT_ID, SUM(O.AMOUNT) AMOUNT, O.PRODUCE_DATE
FROM FOOD_ORDER O
WHERE YEAR(O.PRODUCE_DATE) = '2022' AND MONTH(O.PRODUCE_DATE) = '5'
GROUP BY O.PRODUCT_ID) O
ON O.PRODUCT_ID = P.PRODUCT_ID
ORDER BY TOTAL_SALES DESC, PRODUCT_ID

