-- 코드를 입력하세요
SELECT DISTINCT R.CAR_ID FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY R
LEFT JOIN CAR_RENTAL_COMPANY_CAR C
ON R.CAR_ID = C.CAR_ID
WHERE (R.START_DATE BETWEEN '2022-10-01' AND '2022-10-31') AND C.CAR_TYPE = '세단'
ORDER BY R.CAR_ID DESC