-- 코드를 작성해주세요
SELECT I.ID, NAME.FISH_NAME, N.LENGTH
FROM FISH_INFO I
JOIN 
(SELECT I.FISH_TYPE, MAX(I.LENGTH) LENGTH
FROM FISH_INFO I
GROUP BY I.FISH_TYPE) N
ON N.FISH_TYPE = I.FISH_TYPE AND N.LENGTH = I.LENGTH
LEFT JOIN FISH_NAME_INFO NAME
ON NAME.FISH_TYPE = I.FISH_TYPE
