-- 코드를 입력하세요
SELECT CONCAT("/home/grep/src/", G.BOARD_ID, "/", G.FILE_ID, G.FILE_NAME, G.FILE_EXT) AS FILE_PATH
FROM USED_GOODS_FILE G
JOIN (SELECT BOARD_ID FROM USED_GOODS_BOARD ORDER BY VIEWS DESC LIMIT 1) B
ON G.BOARD_ID = B.BOARD_ID
ORDER BY G.FILE_ID DESC