-- 코드를 입력하세요
SELECT DISTINCT B.CATEGORY, SUM(S.SALES) AS TOTAL_SALES FROM BOOK B
RIGHT JOIN BOOK_SALES S
ON B.BOOK_ID = S.BOOK_ID
WHERE DATE(S.SALES_DATE) <= '2022-01-31'
GROUP BY B.CATEGORY
ORDER BY B.CATEGORY