-- 코드를 입력하세요

SELECT A.CATEGORY, A.PRICE AS MAX_PRICE, A.PRODUCT_NAME
FROM FOOD_PRODUCT A
JOIN 
(SELECT CATEGORY, MAX(PRICE) AS MAX_PRICE
FROM FOOD_PRODUCT
GROUP BY CATEGORY
HAVING CATEGORY IN ('식용유', '과자', '국', '김치')
ORDER BY PRICE DESC) B
ON A.PRICE = B.MAX_PRICE AND A.CATEGORY = B.CATEGORY
ORDER BY PRICE DESC;

# SELECT * FROM FOOD_PRODUCT;